name: Trying it out
favicon: null
layout_spectrum: 0.88636
typography_spectrum: 0.17781571322120726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#635479'
    - '#cacaca'
    - '#939393'
    - '#292929'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
