name: Trying it out
favicon: null
layout_spectrum: 0.20669535617344081
typography_spectrum: 0.17781571322120726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#635479'
    - '#cacaca'
    - '#939393'
    - '#292929'
  brandStrength: 0.5
  lightness: 0.8377130723092705
  saturation: 0.2210310527589172
  rhythmicContrast: 0.9515161816962063
purpose: []
